project:
  type: website
  output-dir: "docs"

website:
  title: "Jack Daniel Johncox"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

