project:
  type: website
  output-dir: docs

website:
  title: "Jack Daniel Johncox"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Bio"
        file: about.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/jackdjohncox

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

