---
title: "Brazil Research Tour - 2 Days Out"
date: 2026-05-28
description: "Prepping"
categories: [Work, Film, Travel]
---

In two days I leave for over a month. I don't speak the language, and apparently shorts are not well received in some areas. I am incredibly excited, but it has also been a long time since I have been away from home like this. Much less, the closest example I have is a youth camp on the Frio River haha. This is much different. At first I was slightly nervous about it all as you can imagine, but telling myself how unique this is makes it more exciting. With how often we will be flying, I will be unable to take film or my camera on this trip... So I bought a new one. Known for its film simulations: the FujiFilm X100. I figure this is a great time to learn digital photography.

Maybe I will also detox technology while away. Try to escape the black hole of Instagram Reels and Youtube. I've got some books I need to read, the first of which is The Crossing by Cormac McCarthy. I plan on posting when I return with some pictures for anyone to enjoy. 

Peace out